services:
  - type: web
    name: Prototipe-IntroBot
    runtime: docker
    port: 5005  # ¡Debe coincidir con el puerto del Dockerfile y el CMD de Rasa!
    env: python
    build:
      dockerfile: Dockerfile
    envVars:
      - key: SANIC_WORKERS
        value: "1"  # Reduce workers para evitar sobrecarga en plan free
    plan: free
