services:
  - type: web
    name: Prototipe-IntroBot
    runtime: docker
    port: 10000
    env: python
    build:
      dockerfile: Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: SANIC_WORKERS
        value: "1"
    plan: free  # Cambia a "starter" o "standard" para producción